trigger:
  - master
  - develop

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if notIn(variables['Build.SourceBranchName'], 'master', 'develop') }}:
    buildImage: false
    deployService: false
    deployEnvironment: 'no'
    imageTags: 'no'
    serviceName: 'no'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    buildImage: true
    deployService: true
    deployEnvironment: development
    imageTags: |
      $(Build.BuildId)
      develop
    serviceName: itlab_develop-back
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildImage: true
    deployService: true
    deployEnvironment: production
    imageTags: |
      $(Build.BuildId)
      latest
    serviceName: itlab_back

stages:
- stage: Build
  jobs:
  - job: Database
    steps:
    - script: ./build.sh --target pack-db --pack-version-postfix $(Build.BuildId)
    - publish: packs
      artifact: itlab-database-nuget

  - job: Backend
    steps:
    - script: ./build.sh --build-id $(Build.BuildId)
    - publish: deploy
      artifact: itlab-back
- stage: packInDocker
  condition: and(succeeded(), ${{variables.buildImage}})
  jobs:
  - job: packApi
    steps:
      - checkout: none
      - download: current
        artifact: itlab-back
      - task: Docker@2
        inputs:
          containerRegistry: 'rtuitlab connection by admin'
          repository: 'rtuitlab/itlab-back'
          command: 'buildAndPush'
          Dockerfile: '$(Pipeline.Workspace)/itlab-back/Dockerfile'
          buildContext: '$(Pipeline.Workspace)/itlab-back'
          tags: ${{variables.imageTags}}
- stage: UpdateService
  condition: and(succeeded(), ${{variables.deployService}})
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: deployEnvironment
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/itlab-back:$(Build.BuildId) ${{variables.serviceName}}'
                readyTimeout: '20000'
