trigger:
  - master
  - develop

name: $(BuildID)-$(Build.SourceBranchName)

variables:
  nuget_package_number: '1.1.$(Build.BuildId)'

pool:
  name: Default
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: BackEnd/BackEnd.csproj
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: itlab-back-$(Build.SourceBranchName)'
  inputs:
    ArtifactName: 'itlab-back-$(Build.SourceBranchName)'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/Models.PublicAPI.csproj;**/Extensions.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: nuget_package_number

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: itlab-back-$(Build.SourceBranchName)-nuget'
  inputs:
    ArtifactName: 'itlab-back-$(Build.SourceBranchName)-nuget'
