trigger:
  - master
name: $(BuildID)

variables:
  nuget_package_number: '1.1.$(BuildID)'

pool:
  name: Default
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: BackEnd/BackEnd.csproj
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: itlab-back-master'
  inputs:
    ArtifactName: 'itlab-back-master'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/Models.PublicAPI.csproj;**/Extensions.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: nuget_package_number

- task: NuGetCommand@2
  displayName: 'Push to Nuget.org'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget org'