trigger:
  - develop

name: $(BuildID)
pool:
  name: Default
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: BackEnd/BackEnd.csproj
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: file-creator@5
  inputs:
    fileoverwrite: true
    filepath: '$(Build.ArtifactStagingDirectory)/build.json'
    filecontent: '{
              "BuildInformation": {
                "BuildId": "$(Build.BuildId)",
      "BuildDateString": ""
        }
      }'
    endWithNewLine: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: itlab-back-develop'
  inputs:
    ArtifactName: 'itlab-back-develop'