trigger:
  - master
  - develop

name: $(BuildID)-$(Build.SourceBranchName)

variables:
  nuget_package_number: '1.1.$(Build.BuildId)'

jobs:
- job: Backend
  pool:
    name: Default
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: BackEnd/BackEnd.csproj
      arguments: '-o $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: itlab-back-build'
    inputs:
      ArtifactName: 'itlab-back-build'

- job: Identity
  pool:
    name: Default
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: IdentityServer/IdentityServer.csproj
      arguments: '-o $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: itlab-identity-build'
    inputs:
      ArtifactName: 'itlab-identity-build'

- job: Nuget
  pool:
    name: Default
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: '**/Models.PublicAPI.csproj;**/Extensions.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: nuget_package_number

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: itlab-back-nuget'
    inputs:
      ArtifactName: 'itlab-back-nuget'
