FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY LaboratoryWorkControl.sln ./
COPY BackEnd/BackEnd.csproj BackEnd/
COPY Models/Models.csproj Models/
COPY Extensions/Extensions.csproj Extensions/
COPY Models.PublicAPI/Models.PublicAPI.csproj Models.PublicAPI/
COPY ApiSchemaCLI/ApiSchemaCLI.csproj ApiSchemaCLI/
COPY WebApp.Configure/WebApp.Configure.csproj WebApp.Configure/
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/BackEnd
RUN rm -rf DataBase/Migrations
RUN dotnet build -o /app
RUN dotnet ef migrations add DevelopMigration

FROM build AS publish
RUN dotnet publish -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "BackEnd.dll"]
